// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB6I9hsvLR3espGNiqqvOAP9nX1T5OQDs',
    appId: '1:173549307966:web:ec3e7732c50f31525b696f',
    messagingSenderId: '173549307966',
    projectId: 'care-connect-d9357',
    authDomain: 'care-connect-d9357.firebaseapp.com',
    storageBucket: 'care-connect-d9357.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4CGRZUajDeF_cxq-Zx22iZQVh16W-7VQ',
    appId: '1:173549307966:android:4d07327218e35d265b696f',
    messagingSenderId: '173549307966',
    projectId: 'care-connect-d9357',
    storageBucket: 'care-connect-d9357.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ8Pu8LsmGl786BGTmbrHXs5FuPPJ4l6s',
    appId: '1:173549307966:ios:bca4b4b9c93f13205b696f',
    messagingSenderId: '173549307966',
    projectId: 'care-connect-d9357',
    storageBucket: 'care-connect-d9357.firebasestorage.app',
    iosBundleId: 'com.example.careConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ8Pu8LsmGl786BGTmbrHXs5FuPPJ4l6s',
    appId: '1:173549307966:ios:bca4b4b9c93f13205b696f',
    messagingSenderId: '173549307966',
    projectId: 'care-connect-d9357',
    storageBucket: 'care-connect-d9357.firebasestorage.app',
    iosBundleId: 'com.example.careConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB6I9hsvLR3espGNiqqvOAP9nX1T5OQDs',
    appId: '1:173549307966:web:2f059fd330035e4f5b696f',
    messagingSenderId: '173549307966',
    projectId: 'care-connect-d9357',
    authDomain: 'care-connect-d9357.firebaseapp.com',
    storageBucket: 'care-connect-d9357.firebasestorage.app',
  );
}
